var victims = [
		'Shelly D. Bland, 25, Tuttle',
		'Carrol June "Chip" Fields, 48, Guthrie',
		'Rona Linn Kuehner-Chafey, 35, Oklahoma City',
		'Carrie Ann Lenz, 26, Chotaw',
		'Kenneth Glenn McCullough, 36, Edmond',
		'Cynthia L. Brown, 26, Oklahoma City',
		'Donald Ray Leonard, 50, Edmond',
		'Mickey B. Maroney, 50, Oklahoma City',
		'Linda G. McKinney, 47, Oklahoma City',
		'Kathy Lynn Seidl, 39, Bethel',
		'Alan G. Whicher, 40, Edmond',
		'Ted L. Allen, 48, Norman',
		'Peter R. Avillanoza, 56, Oklahoma City',
		'David Neil Burkett, 47, Oklahoma City',
		'Donald Earl Burns, Sr., 63, Oklahoma City',
		'Kimberly Kay Clark, 39, Oklahoma City',
		'Susan Jane Ferrell, 37, Oklahoma City',
		'Dr. George Michael Howard, 45, Vallejo, Calif.',
		'Antonio "Tony" C. Reyes, 55, Edmond',
		'Lanny Lee David Scroggins, 46, Yukon',
		'Leora Lee Sells, 57, Oklahoma City',
		'Jules A. Valdez, 51, Edmond',
		'David Jack Walker, 54, Edmond',
		'Michael D. Weaver, 54, Edmond',
		'Frances "Fran" Ann Williams, 48, Oklahoma City',
		'Clarence Eugene Wilson, Sr. 49, Oklahoma',
		'Diane E. (Hollingsworth) Althouse, 45, Edmond',
		'Andrea Yvette Blanton, 33, Oklahoma City',
		'Kim R. Cousins, 33, Midwest City',
		'Diana Lynne Day, 38, Oklahoma City',
		'Castine Brooks Hearn Deveroux, 49, Oklahoma City',
		'Judy J. (Froh) Fisher, 45, Oklahoma City',
		'Linda Louise Florence, 43, Oklahoma City',
		'J. Colleen Guiles, 59, Oklahoma City',
		'Thompson Eugene "Gene" Hodges, Jr., 54, Norman',
		'Ann Kreymborg, 57, Oklahoma City',
		'Teresa Lea Taylor Lauderdale, 41, Shawnee',
		'Mary Leasure-Rentie, 39, Bethany',
		'James A. McCarthy II, 53, Edmond',
		'Betsy J. (Beebe) McGonnell, 47, Norman',
		'Patricia Ann Nix, 47, Edmond',
		'Terry Smith Rees, 41, Midwest City',
		'John Thomas Stewart, 51, Oklahoma City',
		'John Karl Van Ess III, 67, Chickasha',
		'Jo Ann Whittenberg, 35, Oklahoma City',
		'Sgt. Benjamin LaRanzo Davis, USMC, 29, Edmond',
		'Capt. Randolph A. Guzman, USMC, 28, Castro Valley, Calif.',
		'Olen Burl Bloomer, 61, Moore',
		'James E. Boles, 50, Oklahoma City',
		'Dr. Margaret L. "Peggy" Clark, 42, Chickasha',
		'Richard "Dick" Cummins, 55, Mustang',
		'Doris "Adele" Higginbottom, 44, Oklahoma City',
		'Carole Sue Khalil, 50, Oklahoma City',
		'Rheta Bender Long, 60, Oklahoma City',
		'Paul Gregory Beatty Broxterman, 42, Edmond',
		'Paul D. Ice, 42, Midwest City',
		'Claude Authur Medearis, S.S.A., 41, Norman',
		'Lucio Aleman, Jr., 33, Oklahoma City',
		'Mark Allen Bolte, 28, Oklahoma City',
		'Michael Carrillo, 44, Oklahoma City',
		'Larry James Jones, 46. Yukon',
		'James K. Martin, 34, Oklahoma City',
		'Ronota Ann Newberry-Woodbridge, 31, Edmond',
		'Jerry Lee Parker, 45, Norman',
		'Michelle A. Reeder, 33, Oklahoma City',
		'Rick L. Tomlin, 46, Piedmont',
		'Johnny Allen Wade, 42, Edmond',
		'John A. Youngblood, 52, Yukon',
		'Sgt. 1st Class Lola Bolden, U.S. Army, 40, Birmingham, Ala.',
		'Karen Gist Carr, 32, Midwest City',
		'Peggy Louise Holland, 37, Oklahoma City',
		'John C. Moss III., 50, Oklahoma City',
		'Victoria (Vickey) L. Sohn, 36, Moore',
		'Dolores (Dee) Stratton, 51, Moore',
		'Kayla Marie Titsworth, 3.50, Lawton',
		'Wanda Lee Watkins, 49, Oklahoma City',
		'Harley Richard Cottingham, 46, Oklahoma City',
		'Peter L. DeMaster, 44, Oklahoma City',
		'Norma "Jean" Johnson, 62, Oklahoma City',
		'Larry L. Turner, 42, Oklahoma City',
		'Robert G. Westberry, 57, Oklahoma City',
		'Woodrow Clifford "Woody" Brady, 41, Oklahoma City',
		'Kimberly Ruth Burgess, 29, Oklahoma City',
		'Kathy A. Finley, 44, Yukon',
		'Jamie (Fialkowski) Genzer, 32, Wellston',
		'Sheila R. Gigger-Driver, 28, Oklahoma City',
		'Linda Coleen Housley, 53, Oklahoma City',
		'Robbin Ann Huff, 37, Bethany',
		'Christi Yolanda Jenkins, 32, Edmond',
		'Alvin J. Justes, 54, Oklahoma City',
		'Valerie Jo Koelsch, 33, Oklahoma City',
		'Kathy Cagle Leinen, 47, Oklahoma City',
		'Claudette (Duke) Meek, 43, Oklahoma City',
		'Frankie Ann Merrell, 23, Oklahoma City',
		'Jill Diane Randolph, 27, Oklahoma City',
		'Claudine Ritter, 48, Oklahoma City',
		'Christy Rosas, 22, Moore',
		'Sonja Lynn Sanders, 27, Moore',
		'Karan Howell Shepherd, 27, Moore',
		'Victoria Jeanette Texter, 37, Oklahoma City',
		'Virginia M. Thompson, 56, El Reno',
		'Tresia Jo "Mathes" Worton, 28, Oklahoma City',
		'Baylee Almon, 1, Oklahoma City',
		'Danielle Nicole Bell, 15 months, Oklahoma City',
		'Zachary Taylor Chavez, 3, Oklahoma City',
		'Dana LeAnne Cooper, 24, Moore',
		'Anthony Christopher Cooper II, 2, Moore',
		'Antonio Ansara Cooper Jr., 6 months, Midwest City',
		'Aaron M. Coverdale, 5.50, Oklahoma City',
		'Elijah S. Coverdale, 2.50, Oklahoma City',
		'Jaci Rae Coyne, 14 months, Moore',
		'Brenda Faye Daniels, 42, Oklahoma City',
		'Taylor Santoi Eaves, 8 months, Midwest City',
		'Tevin D\'Aundrae Garrett, 16 months, Midwest City',
		'Kevin "Lee" Gottshall II, 6 months, Norman',
		'Wanda Lee Howell, 34, Spencer',
		'Blake Ryan Kennedy, 1.50, Amber',
		'Dominique Ravae (Johnson)-London, 2, Oklahoma City',
		'Chase Dalton Smith, 3, Oklahoma City',
		'Colton Wade Smith, 2, Oklahoma City',
		'Scott D. Williams, 24, Tuttle',
		'Teresa Antionette Alexander, 33, Oklahoma City',
		'Richard A. Allen, 46, Oklahoma City',
		'Pamela Cleveland Argo, 36, Oklahoma City',
		'Saundra G. (Sandy) Avery, 34, Midwest City',
		'Calvin Battle, 62, Oklahoma City',
		'Peola Battle, 56, Oklahoma City',
		'Oleta C. Biddy, 54, Tuttle',
		'Casandra Kay Booker, 25, Oklahoma City',
		'Carol Louise Bowers, 53, Yukon',
		'Peachlyn Bradley, 3, Oklahoma City',
		'Gabreon D.L. Bruce, 3 months, Oklahoma City',
		'Katherine Louise Cregan, 60, Oklahoma City',
		'Ashley Megan Eckles, 4, Guthrie',
		'Don Fritzler, 64, Oklahoma City',
		'Mary Anne Fritzler, 57, Oklahoma City',
		'Laura Jane Garrison, 61, Oklahoma City',
		'Margaret Betterton Goodson, 54, Oklahoma City',
		'Ethel L. Griffin, 55, Edmond',
		'Cheryl E. Hammon, 44, Oklahoma City',
		'Ronald Vernon Harding, Sr., 55, Oklahoma City',
		'Thomas Lynn Hawthorne, Sr., 52, Choctaw',
		'Dr. Charles E. Hurlburt, 73, Oklahoma City',
		'Jean Nutting Hurlburt, 67, Oklahoma City',
		'Raymond "Lee" Johnson, 59, Oklahoma City',
		'LaKesha Richardson Levy, 21, Midwest City',
		'Aurelia Donna Luster, 43, Guthrie',
		'Robert Lee Luster, Jr., 45, Guthrie',
		'Rev. Gilbert X. Martinez, 35, Oklahoma City',
		'Cartney J. McRaven, 19, Midwest City',
		'Derwin W. Miller, 27, Oklahoma City',
		'Eula Leigh Mitchell, 64, Oklahoma City',
		'Emilio Tapia, 50, Oklahoma City',
		'Charlotte Andrea Lewis Thomas, 43, Oklahoma City',
		'Michael George Thompson, 47, Yukon',
		'LaRue A. Treanor, 55, Guthrie',
		'Luther H. Treanor, 61, Guthrie',
		'Robert N. Walker, Jr., 52, Oklahoma City',
		'Julie Marie Welch, 23, Oklahoma City',
		'W. Stephen Williams, 42, Cashion',
		'Sharon Louise Wood-Chesnut, 47, Oklahoma City',
		'Steven Douglas Curry, 44, Norman',
		'Michael L. Loudenslager, 48, Harrah',
		'Rebecca Needham Anderson, 37, Midwest City',
		'Anita Christine Hightower, 27, Oklahoma City',
		'Kathryn Elizabeth Ridley, 24, Oklahoma City',
		'Robert N. Chipman, 51, Edmond',
		'Trudy Jean Rigney, 31, Midwest City',
];